#!/bin/sh
# Emit the Homebrew formula for a release tag to stdout.
#
#   bump.sh <tag> <dir>
#     <tag>  release tag, e.g. v0.2.0
#     <dir>  directory holding the four goldfinger-<os>-<arch>.sha256 sidecars
#
# The committed packaging/homebrew/goldfinger.rb is this script's output for the
# current release; the release workflow re-runs it per tag and pushes the result
# to the redscaresu/homebrew-tap repo. One generator, no drift.
set -eu

tag="${1:?usage: bump.sh <tag> <dir>}"
dir="${2:?usage: bump.sh <tag> <dir>}"
ver="${tag#v}"

sha() { cut -d' ' -f1 <"${dir}/goldfinger-$1.sha256"; }
url() { echo "https://github.com/redscaresu/goldfinger/releases/download/${tag}/goldfinger-$1"; }

cat <<EOF
# Generated by packaging/homebrew/bump.sh — do not edit by hand.
# Regenerate with: packaging/homebrew/bump.sh ${tag} <dir-with-.sha256-sidecars>
class Goldfinger < Formula
  desc "SRE toolkit for fleet-wide GitHub repo changes (ghorg + multi-gitter)"
  homepage "https://github.com/redscaresu/goldfinger"
  version "${ver}"
  license "Apache-2.0"

  # goldfinger orchestrates these two CLIs (it shells out to them on PATH); both
  # are in homebrew-core, so a formula install pulls them in automatically.
  depends_on "ghorg"
  depends_on "multi-gitter"

  on_macos do
    on_arm do
      url "$(url darwin-arm64)"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "$(url darwin-amd64)"
      sha256 "$(sha darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$(url linux-arm64)"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "$(url linux-amd64)"
      sha256 "$(sha linux-amd64)"
    end
  end

  def install
    # Release assets are named goldfinger-<os>-<arch>; install the one Homebrew
    # downloaded as a plain \`goldfinger\`.
    bin.install Dir["goldfinger-*"].first => "goldfinger"
  end

  test do
    assert_match "goldfinger version", shell_output("#{bin}/goldfinger --version")
  end
end
EOF
