# Generated by packaging/homebrew/bump.sh — do not edit by hand.
# Regenerate with: packaging/homebrew/bump.sh v0.2.0 <dir-with-.sha256-sidecars>
class Goldfinger < Formula
  desc "SRE toolkit for fleet-wide GitHub repo changes (ghorg + multi-gitter)"
  homepage "https://github.com/redscaresu/goldfinger"
  version "0.2.0"
  license "Apache-2.0"

  # goldfinger orchestrates these two CLIs (it shells out to them on PATH); both
  # are in homebrew-core, so a formula install pulls them in automatically.
  depends_on "ghorg"
  depends_on "multi-gitter"

  on_macos do
    on_arm do
      url "https://github.com/redscaresu/goldfinger/releases/download/v0.2.0/goldfinger-darwin-arm64"
      sha256 "26c1c1220ed5dea633135fd14bd0cb3e55ca247014dc943adebec2a7fdeeffc7"
    end
    on_intel do
      url "https://github.com/redscaresu/goldfinger/releases/download/v0.2.0/goldfinger-darwin-amd64"
      sha256 "d5f6f206a9f9504a2629b5c18a41cbffdf7503655336ca0b21c3574952aec7ae"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/redscaresu/goldfinger/releases/download/v0.2.0/goldfinger-linux-arm64"
      sha256 "8306b3ca271b5517f55833903c95aff4d27402a64a8c953f187084e9a89143b5"
    end
    on_intel do
      url "https://github.com/redscaresu/goldfinger/releases/download/v0.2.0/goldfinger-linux-amd64"
      sha256 "5388b3a27930627405fd9bb681094aa8f8852fda908c10db6d04c988120eee75"
    end
  end

  def install
    # Release assets are named goldfinger-<os>-<arch>; install the one Homebrew
    # downloaded as a plain `goldfinger`.
    bin.install Dir["goldfinger-*"].first => "goldfinger"
  end

  test do
    assert_match "goldfinger version", shell_output("#{bin}/goldfinger --version")
  end
end
