use chrono::Local;
use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;

pub struct GenesisAgent;

impl GenesisAgent {
    pub fn record_opportunity(query: &str) {
        // We write to the current working directory, which should be the user's workspace root
        let path = Path::new("GENESIS_TASKS.md");

        let exists = path.exists();

        let timestamp = Local::now().format("%Y-%m-%d %H:%M:%S");
        let task_entry = format!(
            "- [ ] **Implement '{}'** <!-- created: {} -->\n    - *Context*: Search returned 0 results (Deep Void verified).\n    - *Action*: Scaffold this missing component.\n",
            query, timestamp
        );

        match OpenOptions::new().create(true).append(true).open(path) {
            Ok(mut file) => {
                if !exists {
                    let header = "# Genesis Tasks\n\n> Auto-generated by Antigravity Swarm based on search voids.\n\n";
                    if let Err(e) = file.write_all(header.as_bytes()) {
                        tracing::error!("Failed to write Genesis header: {}", e);
                    }
                }

                if let Err(e) = file.write_all(task_entry.as_bytes()) {
                    tracing::error!("Failed to append Genesis task: {}", e);
                } else {
                    tracing::info!("Genesis Task Recorded: {}", query);
                }
            }
            Err(e) => {
                tracing::error!("Failed to open GENESIS_TASKS.md: {}", e);
            }
        }
    }
}
