/**
 * Auto provider-defs loader — first-class drift killer for @ranch/roost.
 *
 * The static PROVIDER_DEFS in data.ts is curated by hand. Policy layers
 * (tau's TAU_PROVIDER_POLICY, herd fragments, pitchfork configs) can name
 * providers the static catalog doesn't know yet. Previously that produced a
 * `[roost] DRIFT` skip-warning and required a hand edit to data.ts for every
 * new provider. This loader closes that loop:
 *
 *   1. static defs win — curated entries are never overwritten;
 *   2. drop-in defs from providers.d/ merge next (first-class extension
 *      without touching data.ts);
 *   3. any still-missing required id gets a synthesized best-effort def
 *      (known public endpoint when we have one, keyEnv derived by
 *      convention, marked autoGenerated so consumers can tell it apart
 *      from a curated def).
 *
 * The loader is a pure function: it takes the static defs as an argument
 * instead of importing data.ts, so out-of-tree consumers (tau's compat
 * layer, which may be running against an embedded fallback snapshot) can
 * use it with whatever defs they resolved. In-tree consumers should use
 * loadCatalogProviderDefs(), which binds the live PROVIDER_DEFS.
 */

import type { ProviderDef } from "./types.ts";
import { PROVIDER_DEFS } from "./data.ts";

/**
 * Curated public OpenAI-compatible endpoints for providers that are not
 * (yet) in the static catalog. Only entries verified against the
 * provider's own docs belong here — never guess a URL.
 */
export const KNOWN_ENDPOINTS: Readonly<Record<string, string>> = {
  moonshot: "https://api.moonshot.ai/v1",
};

/** Convention: provider id -> env var holding its key, e.g. "groq" -> "GROQ_API_KEY". */
export function keyEnvFor(id: string): string {
  return `${id.replace(/[^a-zA-Z0-9]+/g, "_").toUpperCase()}_API_KEY`;
}

/** Convention: provider id -> human display name, e.g. "moonshot" -> "Moonshot". */
export function displayNameFor(id: string): string {
  return id
    .split(/[-_]+/)
    .map((w) => (w ? w[0]!.toUpperCase() + w.slice(1) : w))
    .join(" ");
}

/**
 * Synthesize a best-effort ProviderDef for an id with no curated entry.
 * Prefers KNOWN_ENDPOINTS, then an explicit endpoint override; when neither
 * exists the def carries an empty baseUrl and stays marked autoGenerated so
 * a curator can spot it and promote it to data.ts.
 */
export function synthesizeProviderDef(id: string, endpoint?: string): ProviderDef {
  const baseUrl = endpoint ?? KNOWN_ENDPOINTS[id] ?? "";
  return {
    name: id,
    displayName: displayNameFor(id),
    baseUrl,
    keyEnv: keyEnvFor(id),
    auth: "bearer",
    adapter: "openai",
    seeds: [],
    autoGenerated: true,
  };
}

export interface AutoLoadOptions {
  /** Ids that must resolve (e.g. Object.keys(TAU_PROVIDER_POLICY)). */
  requiredIds?: readonly string[];
  /** Drop-in defs (from providers.d/) — override static, never synthesized. */
  dropIns?: readonly ProviderDef[];
  /** Endpoint overrides for synthesis, merged over KNOWN_ENDPOINTS. */
  endpoints?: Readonly<Record<string, string>>;
  /** Called once per synthesized id; defaults to console.warn. */
  onSynthesize?: (id: string, def: ProviderDef) => void;
}

export interface AutoLoadResult {
  /** Static + drop-ins + synthesized, in that precedence. */
  defs: ProviderDef[];
  /** Ids that were auto-synthesized (had no static or drop-in def). */
  synthesized: string[];
  /** Lookup by name over the merged set. */
  byName: Map<string, ProviderDef>;
}

/**
 * Merge static defs, drop-ins, and synthesized defs into one resolved set.
 * Static entries are never overwritten; drop-ins override statics;
 * synthesized defs fill whatever requiredIds remain uncovered.
 */
export function loadProviderDefs(
  staticDefs: readonly ProviderDef[],
  opts: AutoLoadOptions = {},
): AutoLoadResult {
  const byName = new Map<string, ProviderDef>();
  for (const d of staticDefs) byName.set(d.name, d);
  for (const d of opts.dropIns ?? []) byName.set(d.name, d);

  const synthesized: string[] = [];
  const endpoints = { ...KNOWN_ENDPOINTS, ...(opts.endpoints ?? {}) };
  const notify = opts.onSynthesize ?? ((id, def) => console.warn(
    `[roost] provider "${id}" has no curated PROVIDER_DEFS entry — ` +
    `auto-synthesized best-effort def (keyEnv ${def.keyEnv}). ` +
    `Promote it to ranch/mesh/catalog/src/data.ts to silence this.`,
  ));
  for (const id of opts.requiredIds ?? []) {
    if (!byName.has(id)) {
      const def = synthesizeProviderDef(id, endpoints[id]);
      byName.set(id, def);
      synthesized.push(id);
      notify(id, def);
    }
  }
  return { defs: [...byName.values()], synthesized, byName };
}

/**
 * In-tree convenience: bind the live catalog PROVIDER_DEFS.
 * Out-of-tree consumers (tau compat) should call loadProviderDefs()
 * directly with whatever defs they resolved.
 */
export function loadCatalogProviderDefs(opts: AutoLoadOptions = {}): AutoLoadResult {
  return loadProviderDefs(PROVIDER_DEFS, opts);
}

/**
 * Read drop-in provider defs from a providers.d-style directory.
 * Each *.json file holds either a single ProviderDef or
 * { "providers": ProviderDef[] }. Missing dir (or unreadable files)
 * yields [] — drop-ins are optional by design.
 */
export async function loadDropInDefs(dir: string): Promise<ProviderDef[]> {
  const { readdir, readFile } = await import("node:fs/promises");
  const { join } = await import("node:path");
  let files: string[];
  try {
    files = (await readdir(dir)).filter((f) => f.endsWith(".json")).sort();
  } catch {
    return [];
  }
  const out: ProviderDef[] = [];
  for (const f of files) {
    try {
      const raw = JSON.parse(await readFile(join(dir, f), "utf8"));
      const defs: ProviderDef[] = Array.isArray(raw) ? raw : raw.providers ?? [raw];
      for (const d of defs) {
        if (d && typeof d.name === "string") out.push(d);
      }
    } catch {
      // A bad drop-in never breaks the catalog; it just doesn't load.
    }
  }
  return out;
}
