[package]
name = "gh-search-core"
edition.workspace = true
authors.workspace = true
license.workspace = true
version = "0.1.0"

[dependencies]
gh-search-cache = { path = "../cache" }
gh-search-context = { path = "../context" }
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
regex = "1.10"
base64 = "0.22"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
urlencoding.workspace = true
thiserror.workspace = true
shlex = "1.3"
itertools = "0.14"
dotenvy.workspace = true
rand = "0.8"
tree-sitter = "0.24"
tree-sitter-rust = "0.23"

