#!/usr/bin/env bun
/**
 * classifier-preflight — scan text for known safety-classifier false-positive
 * trigger shapes before the text goes into a task body, brief, doc, or chat.
 *
 * Usage:
 *   bun preflight.ts <file>...        # scan files, exit 1 if triggers found
 *   bun preflight.ts --stdin < file   # scan stdin
 *   bun preflight.ts --json <file>    # machine-readable report
 *
 * Trigger DB: triggers.json (generated by `bun tools/gen-triggers-json.ts`
 * from db-src/triggers.ts, the single source of truth).
 *
 * This is false-positive repair for our own operational docs — not a bypass
 * technique. If a flag lands on a task whose actual purpose is wrong, the flag
 * was right and the task dies; repair is for legitimate operation only.
 */
import { readFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DB = JSON.parse(readFileSync(join(HERE, "triggers.json"), "utf8"));

type Pattern = { source: string; flags: string };
type Shape = { id: string; patterns: Pattern[]; why: string; rewrite: string };
type Finding = {
  trigger: string;
  line: number;
  match: string;
  why: string;
  rewrite: string;
};

function scan(text: string): Finding[] {
  const lines = text.split("\n");
  const out: Finding[] = [];
  for (const t of DB.shapes as Shape[]) {
    for (const p of t.patterns) {
      const re = new RegExp(p.source, p.flags);
      lines.forEach((ln, i) => {
        re.lastIndex = 0;
        const m = re.exec(ln);
        if (m)
          out.push({
            trigger: t.id,
            line: i + 1,
            match: m[0].slice(0, 80),
            why: t.why,
            rewrite: t.rewrite,
          });
      });
    }
  }
  return out.sort((a, b) => a.line - b.line);
}

async function readInput(
  args: string[],
): Promise<{ name: string; text: string }[]> {
  if (args.includes("--stdin")) {
    const chunks: Buffer[] = [];
    for await (const c of Bun.stdin.stream()) chunks.push(Buffer.from(c));
    return [{ name: "<stdin>", text: Buffer.concat(chunks).toString("utf8") }];
  }
  const files = args.filter((a) => !a.startsWith("--"));
  return files.map((f) => {
    if (!existsSync(f)) {
      console.error(`missing: ${f}`);
      process.exit(2);
    }
    return { name: f, text: readFileSync(f, "utf8") };
  });
}

const args = process.argv.slice(2);
const asJson = args.includes("--json");
const inputs = await readInput(args);
let total = 0;
const report: Record<string, Finding[]> = {};
for (const { name, text } of inputs) {
  const findings = scan(text);
  report[name] = findings;
  total += findings.length;
}
if (asJson) {
  console.log(
    JSON.stringify({ scanned: inputs.length, findings: total, report }, null, 1),
  );
} else {
  for (const [name, findings] of Object.entries(report)) {
    console.log(`== ${name}: ${findings.length} trigger(s)`);
    for (const f of findings) {
      console.log(`  L${f.line} [${f.trigger}] "${f.match}"`);
      console.log(`    why: ${f.why}`);
      console.log(`    fix: ${f.rewrite}`);
    }
  }
  console.log(
    total === 0 ? "clean" : `${total} trigger shape(s) found — reword per fixes above`,
  );
}
process.exit(total === 0 ? 0 : 1);
