#!/usr/bin/env bash
# Permanent sovereign helper: export GitHub *web* session for Blackbird code search.
# PAT/GH_TOKEN alone cannot hit github.com/search (Blackbird). user_session cookie can.
#
# Writes:
#   ~/.config/sovereign/github-web-session.env   (sourced by ghas-mcp-stdio.sh)
#   GITHUB_SESSION / GITHUB_SESSIONS
#
# Sources (first win):
#   1) existing GITHUB_SESSIONS / GITHUB_SESSION / GH_WEB_SESSION env
#   2) Firefox cookies.sqlite (GHAS_FIREFOX_PROFILE or profiles.ini + known sovereign profiles)
set -euo pipefail

HOME="${HOME:-/home/toxic}"
OUT_DIR="${HOME}/.config/sovereign"
OUT_ENV="${OUT_DIR}/github-web-session.env"
mkdir -p "$OUT_DIR"

write_env() {
  local sess="$1"
  local src="${2:-unknown}"
  local prof="${3:-}"
  sess="${sess%%,*}"
  sess="${sess//[$'\t\r\n ']/}"
  {
    echo "# generated by ghas-refresh-github-session.sh"
    echo "# source=${src}"
    [[ -n "$prof" ]] && echo "# profile=${prof}"
    echo "# refreshed=$(date -Iseconds)"
    echo "export GITHUB_SESSION=${sess}"
    echo "export GITHUB_SESSIONS=${sess}"
    echo "export GH_WEB_SESSION=${sess}"
    echo "export GHAS_CODE_ENGINE=${GHAS_CODE_ENGINE:-auto}"
    [[ -n "$prof" ]] && echo "export GHAS_FIREFOX_PROFILE=${prof}"
  } >"$OUT_ENV"
  chmod 600 "$OUT_ENV"
  echo "ok ${src} session_len=${#sess} -> $OUT_ENV"
}

if [[ -n "${GITHUB_SESSIONS:-${GITHUB_SESSION:-${GH_WEB_SESSION:-}}}" ]]; then
  sess="${GITHUB_SESSIONS:-${GITHUB_SESSION:-${GH_WEB_SESSION}}}"
  write_env "$sess" "env"
  exit 0
fi

# Collect Firefox profile dirs (order = preference)
declare -a CANDIDATES=()
add_cand() {
  local p="$1"
  [[ -z "$p" ]] && return 0
  [[ -d "$p" ]] || return 0
  local c
  for c in "${CANDIDATES[@]+"${CANDIDATES[@]}"}"; do
    [[ "$c" == "$p" ]] && return 0
  done
  CANDIDATES+=("$p")
}

[[ -n "${GHAS_FIREFOX_PROFILE:-}" ]] && add_cand "$GHAS_FIREFOX_PROFILE"

# Known sovereign default-release first (profiles.ini Default=1 often points at empty stub)
add_cand "${HOME}/.config/mozilla/firefox/g304xzha.default-release"
add_cand "${HOME}/projects/ff-rescue"

for base in \
  "${HOME}/.config/mozilla/firefox" \
  "${HOME}/.mozilla/firefox"; do
  ini="${base}/profiles.ini"
  [[ -f "$ini" ]] || continue
  # Install* Default= path (modern Firefox)
  install_default=$(awk -F= '
    /^\[Install/ { in_inst=1; next }
    /^\[/ { in_inst=0 }
    in_inst && /^Default=/ { print $2; exit }
  ' "$ini")
  if [[ -n "$install_default" ]]; then
    if [[ "$install_default" = /* ]]; then
      add_cand "$install_default"
    else
      add_cand "${base}/${install_default}"
    fi
  fi
  # Every Path=
  while IFS= read -r path; do
    [[ -z "$path" ]] && continue
    if [[ "$path" = /* ]]; then
      add_cand "$path"
    else
      add_cand "${base}/${path}"
    fi
  done < <(awk -F= '/^Path=/ { print $2 }' "$ini")
done

extract_session() {
  local prof="$1"
  local db="${prof}/cookies.sqlite"
  [[ -f "$db" ]] || return 1
  local TMP
  TMP="$(mktemp -d /tmp/ghas-ff-XXXXXX)"
  # shellcheck disable=SC2064
  trap "rm -rf '$TMP'" RETURN
  cp -f "$db" "$TMP/cookies.sqlite"
  [[ -f "${db}-wal" ]] && cp -f "${db}-wal" "$TMP/cookies.sqlite-wal" || true
  [[ -f "${db}-shm" ]] && cp -f "${db}-shm" "$TMP/cookies.sqlite-shm" || true
  python3 - "$TMP/cookies.sqlite" <<'PY'
import sqlite3, sys
db = sys.argv[1]
con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
row = con.execute(
    "SELECT value FROM moz_cookies WHERE host LIKE '%github.com%' AND name='user_session' ORDER BY lastAccessed DESC LIMIT 1"
).fetchone()
print(row[0] if row else "")
PY
}

for PROF in "${CANDIDATES[@]+"${CANDIDATES[@]}"}"; do
  sess=$(extract_session "$PROF" || true)
  if [[ -n "${sess:-}" ]]; then
    write_env "$sess" "firefox" "$PROF"
    exit 0
  fi
done

echo "error: no GITHUB_SESSION and no Firefox user_session cookie (set GHAS_FIREFOX_PROFILE)" >&2
echo "tried profiles:" >&2
for PROF in "${CANDIDATES[@]+"${CANDIDATES[@]}"}"; do
  echo "  - $PROF (cookies=$([ -f "${PROF}/cookies.sqlite" ] && echo yes || echo no))" >&2
done
exit 1
