import { describe, expect, test } from "bun:test";
import {
  displayNameFor,
  keyEnvFor,
  KNOWN_ENDPOINTS,
  loadCatalogProviderDefs,
  loadDropInDefs,
  loadProviderDefs,
  synthesizeProviderDef,
} from "../src/auto-loader.ts";
import { PROVIDER_DEFS } from "../src/data.ts";
import type { ProviderDef } from "../src/types.ts";

const def = (name: string, extra: Partial<ProviderDef> = {}): ProviderDef => ({
  name,
  baseUrl: `https://api.${name}.example/v1`,
  keyEnv: `${name.toUpperCase()}_API_KEY`,
  adapter: "openai",
  seeds: [],
  ...extra,
});

describe("auto provider-defs loader", () => {
  test("static defs pass through untouched", () => {
    const { defs, synthesized } = loadProviderDefs([def("groq")]);
    expect(defs).toHaveLength(1);
    expect(defs[0]!.name).toBe("groq");
    expect(synthesized).toEqual([]);
  });

  test("missing required id is synthesized, not dropped", () => {
    const { defs, synthesized, byName } = loadProviderDefs([def("groq")], {
      requiredIds: ["groq", "moonshot"],
      onSynthesize: () => {},
    });
    expect(synthesized).toEqual(["moonshot"]);
    const m = byName.get("moonshot")!;
    expect(m.keyEnv).toBe("MOONSHOT_API_KEY");
    expect(m.baseUrl).toBe(KNOWN_ENDPOINTS["moonshot"]);
    expect(m.adapter).toBe("openai");
    expect(m.autoGenerated).toBe(true);
    expect(defs.map((d) => d.name).sort()).toEqual(["groq", "moonshot"]);
  });

  test("static def is never overwritten by synthesis", () => {
    const curated = def("moonshot", { baseUrl: "https://curated.example/v1" });
    const { synthesized, byName } = loadProviderDefs([curated], {
      requiredIds: ["moonshot"],
      onSynthesize: () => {},
    });
    expect(synthesized).toEqual([]);
    expect(byName.get("moonshot")!.baseUrl).toBe("https://curated.example/v1");
    expect(byName.get("moonshot")!.autoGenerated).toBeUndefined();
  });

  test("drop-ins override static defs", () => {
    const drop = def("groq", { baseUrl: "https://dropin.example/v1" });
    const { byName } = loadProviderDefs([def("groq")], { dropIns: [drop] });
    expect(byName.get("groq")!.baseUrl).toBe("https://dropin.example/v1");
  });

  test("unknown id without known endpoint synthesizes an honest placeholder", () => {
    const d = synthesizeProviderDef("some-future-provider");
    expect(d.baseUrl).toBe("");
    expect(d.keyEnv).toBe("SOME_FUTURE_PROVIDER_API_KEY");
    expect(d.autoGenerated).toBe(true);
  });

  test("endpoint overrides beat the known-endpoints registry", () => {
    const d = synthesizeProviderDef("moonshot", "https://override.example/v1");
    expect(d.baseUrl).toBe("https://override.example/v1");
  });

  test("keyEnvFor/displayNameFor conventions", () => {
    expect(keyEnvFor("moonshot")).toBe("MOONSHOT_API_KEY");
    expect(keyEnvFor("x-ai")).toBe("X_AI_API_KEY");
    expect(displayNameFor("moonshot")).toBe("Moonshot");
    expect(displayNameFor("openrouter-free")).toBe("Openrouter Free");
  });

  test("loadCatalogProviderDefs binds the live catalog", () => {
    const { defs, byName } = loadCatalogProviderDefs({ onSynthesize: () => {} });
    expect(defs.length).toBeGreaterThanOrEqual(PROVIDER_DEFS.length);
    expect(byName.get("groq")!.keyEnv).toBe("GROQ_API_KEY");
  });

  test("loadDropInDefs returns [] for a missing dir", async () => {
    expect(await loadDropInDefs("/nonexistent-providers.d")).toEqual([]);
  });

  test("loadDropInDefs reads single-def and {providers} shapes", async () => {
    const dir = await import("node:os").then((os) =>
      import("node:path").then((path) => import("node:fs/promises").then(async (fs) => {
        const d = await fs.mkdtemp(path.join(os.tmpdir(), "providers.d-"));
        await fs.writeFile(`${d}/one.json`, JSON.stringify(def("alpha")));
        await fs.writeFile(`${d}/many.json`, JSON.stringify({ providers: [def("beta"), def("gamma")] }));
        await fs.writeFile(`${d}/bad.json`, "{not json");
        return d;
      })),
    );
    const defs = await loadDropInDefs(dir);
    expect(defs.map((d) => d.name).sort()).toEqual(["alpha", "beta", "gamma"]);
  });
});
