/**
 * Codegen tests: the generated artifacts must always match the source of
 * truth. The sync test regenerates into a temp dir and diffs byte-for-byte
 * against the checked-in generated/ files — a stale artifact fails the suite
 * instead of shipping silently.
 */
import { describe, expect, test } from "bun:test";
import { mkdtemp, rm, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildProvidersGo,
  buildProvidersJson,
  buildProvidersRust,
  buildProvidersTauYaml,
  emitAll,
} from "../src/codegen.ts";
import type { CodegenInput } from "../src/codegen.ts";
import type { ProviderDef } from "../src/types.ts";

const here = dirname(fileURLToPath(import.meta.url));
const generatedDir = join(here, "..", "generated");

function sampleDef(over: Partial<ProviderDef> = {}): ProviderDef {
  return {
    name: "groq",
    displayName: "Groq",
    baseUrl: "https://api.groq.com/openai",
    keyEnv: "GROQ_API_KEY",
    adapter: "openai",
    seeds: ["seed-a"],
    ...over,
  };
}

function sampleInput(): CodegenInput {
  return {
    defs: [
      sampleDef(),
      sampleDef({
        name: "herd",
        baseUrl: "http://127.0.0.1:25100",
        keyEnv: "",
        adapter: "static",
        staticModels: ["role-a"],
        seeds: [],
      }),
    ],
    aliases: { "alias-a": ["groq", "live-a"] },
    deadIds: ["dead-1"],
    provenance: "test",
  };
}

describe("providers.json", () => {
  test("emits canonical JSON with providers, seeds, aliases, deadIds", () => {
    const doc = JSON.parse(buildProvidersJson(sampleInput()));
    expect(doc.$schema).toBe("ranch-roost/v1");
    expect(doc.providers).toHaveLength(2);
    expect(doc.providers[0].name).toBe("groq");
    expect(doc.providers[0].adapter).toBe("openai");
    expect(doc.seeds["groq"]).toEqual(["seed-a"]);
    expect(doc.aliases).toEqual({ "alias-a": ["groq", "live-a"] });
    expect(doc.deadIds).toEqual(["dead-1"]);
    expect(typeof doc.seedsContract).toBe("string");
    expect(typeof doc.deadIdsContract).toBe("string");
    expect(doc.generator).toMatch(/DO NOT EDIT/);
  });
  test("omits empty optionals", () => {
    const doc = JSON.parse(buildProvidersJson(sampleInput()));
    expect("modelsPath" in doc.providers[0]).toBe(false);
    expect("enabled" in doc.providers[0]).toBe(false);
  });
});

describe("providers.go", () => {
  test("emits a drop-in Go data file with DO-NOT-EDIT header", () => {
    const go = buildProvidersGo(sampleInput());
    expect(go).toContain("Code generated by @ranch/roost — DO NOT EDIT BY HAND");
    expect(go).toMatch(/^package astmatrix$/m);
    expect(go).toMatch(/var ProviderCatalogDefs = \[\]CatalogProviderDef\{/);
    expect(go).toMatch(/var ProviderCatalogSeeds = map\[string\]\[\]string\{/);
    expect(go).toMatch(/var ProviderCatalogStaticModels = map\[string\]\[\]string\{/);
    expect(go).toMatch(/var ProviderCatalogAliases = map\[string\]\[2\]string\{/);
    expect(go).toMatch(/var ProviderCatalogDeadIDs = \[\]string\{/);
    expect(go).toContain('"groq"');
    expect(go).toContain('"seed-a"');
    expect(go).toContain('"alias-a": {"groq", "live-a"},');
    expect(go).toContain('"dead-1"');
    // The generated type must not collide with herd registry.go's ProviderDef.
    expect(go).toMatch(/type CatalogProviderDef struct/);
    expect(go).not.toMatch(/type ProviderDef struct/);
    expect(go).toContain("RouterLocal:");
    expect(go).toContain("NoAuth:");
    expect(go).toContain("CatalogProvenance");
  });
  test("go output is deterministic across runs", () => {
    const a = buildProvidersGo(sampleInput());
    const b = buildProvidersGo(sampleInput());
    // generatedAt timestamp differs; strip it before comparing
    const strip = (s: string) => s.replace(/\/\/ Generated at: .*\n/, "");
    expect(strip(a)).toBe(strip(b));
  });
});

describe("providers.rs", () => {
  test("emits a Rust data module with DO-NOT-EDIT header", () => {
    const rs = buildProvidersRust(sampleInput());
    expect(rs).toContain("Code generated by @ranch/roost — DO NOT EDIT BY HAND");
    expect(rs).toMatch(/pub const ROOST_PROVIDERS: &\[RoostProvider\] = &\[/);
    expect(rs).toMatch(/pub const ROOST_DEAD_IDS: &\[&str\] =/);
    expect(rs).toMatch(/pub const ROOST_ALIASES: &\[/);
    expect(rs).toMatch(/pub struct RoostProvider \{/);
    expect(rs).toContain('"groq"');
    expect(rs).toContain('"seed-a"');
    expect(rs).toContain('"alias-a"');
    expect(rs).toContain('"dead-1"');
    expect(rs).toContain("pub const ROOST_PROVENANCE");
    // Every wire field flock's overlay merge needs.
    for (const field of [
      "pub name:",
      "pub display_name:",
      "pub base_url:",
      "pub key_env:",
      "pub key_env_alt:",
      "pub adapter:",
      "pub auth:",
      "pub router_local:",
      "pub enabled:",
      "pub seeds:",
      "pub static_models:",
    ]) {
      expect(rs).toContain(field);
    }
    expect(rs).toContain("router_local: false,");
    // static provider carries its model list in the definition.
    expect(rs).toContain('static_models: &["role-a"],');
  });
  test("rust output is deterministic across runs", () => {
    const a = buildProvidersRust(sampleInput());
    const b = buildProvidersRust(sampleInput());
    // generatedAt timestamp differs; strip it before comparing
    const strip = (s: string) => s.replace(/\/\/ Generated at: .*\n/, "");
    expect(strip(a)).toBe(strip(b));
  });
});

describe("tau-models.yml", () => {
  test("emits valid Tau models.yml with DO-NOT-EDIT header and flock/herd", () => {
    const yml = buildProvidersTauYaml(sampleInput());
    expect(yml).toContain("# Code generated by @ranch/roost for Tau — DO NOT EDIT BY HAND.");
    expect(yml).toContain("discovery:");
    expect(yml).toContain("flock:");
    expect(yml).toContain("baseUrl: http://127.0.0.1:25104/v1");
    expect(yml).toContain("herd:");
    expect(yml).toContain("baseUrl: http://127.0.0.1:25100/v1");
    expect(yml).toContain("groq:");
  });
});

describe("generated-artifact sync", () => {
  test("checked-in generated/ matches a fresh codegen (run `bun run build` if this fails)", async () => {
    const dir = await mkdtemp(join(tmpdir(), "prov-gen-"));
    try {
      // Regenerate from the REAL source of truth.
      const { DEAD_MODEL_IDS, MODEL_ALIASES, PROVIDER_DEFS } = await import(
        "../src/data.ts"
      );
      await emitAll(dir, {
        defs: PROVIDER_DEFS,
        aliases: MODEL_ALIASES,
        deadIds: DEAD_MODEL_IDS,
        provenance: "@ranch/roost src/data.ts",
      });
      for (const name of ["providers.json", "providers.go", "providers.rs", "tau-models.yml"]) {
        const fresh = await readFile(join(dir, name), "utf8");
        let checkedIn: string;
        try {
          checkedIn = await readFile(join(generatedDir, name), "utf8");
        } catch {
          throw new Error(
            `generated/${name} is not checked in — run \`bun run build\` in packages/providers`,
          );
        }
        const norm = (s: string) =>
          name === "providers.go" || name === "providers.rs"
            ? s.replace(/\/\/ Generated at: .*\n/, "")
            : s.replace(/"generatedAt": ".*",\n/, "").replace(/# Generated at: .*\n/, "");
        expect(
          norm(fresh),
          `generated/${name} is stale — run \`bun run build\` in packages/providers`,
        ).toBe(norm(checkedIn));
      }
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  test("herd consumer copy of providers.go matches canonical codegen", async () => {
    // The Go herd consumes the generated artifact as a checked-in copy at
    // <herd-astmatrix-dir>/providers_generated.go. It must be byte-identical
    // to the canonical generated/providers.go (modulo the Generated-at stamp)
    // — never hand-edited. Skips when no herd checkout is present.
    const candidates = [
      process.env.HERD_ASTMATRIX_DIR,
      "/home/toxic/estate/ranch/mesh/router/herd/internal/astmatrix",
    ].filter((p): p is string => typeof p === "string" && p.length > 0);
    let consumerPath = "";
    let consumer = "";
    for (const dir of candidates) {
      try {
        consumer = await readFile(join(dir, "providers_generated.go"), "utf8");
        consumerPath = join(dir, "providers_generated.go");
        break;
      } catch {
        // try next candidate
      }
    }
    if (!consumerPath) {
      console.log("skip: no herd checkout present");
      return;
    }
    const canonical = await readFile(join(generatedDir, "providers.go"), "utf8");
    const norm = (s: string) => s.replace(/\/\/ Generated at: .*\n/, "");
    expect(
      norm(consumer),
      `herd providers_generated.go is stale or hand-edited — copy generated/providers.go to ${consumerPath}`,
    ).toBe(norm(canonical));
  });
});
